[APARENCIA]
tema = Drcl Night
fonte = <PySide2.QtGui.QFont(MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0,Normal) at 0x000001D37FC2FFC0>

[sqlite]
user_db_path = DIGITALIZACAO\2rgiScanDB\banco.db

[postgresql]
host = ip do servidor do banco de dados
port = porta do banco de dados
database = rgiscan_db
user = postgres
password = senha do banco de dados

[REDES]
servidor = \\corporativo
# Caminhos repetidos por questão de respeitar a ordem de documentos diferente que no entanto, usam a 
# mesma pasta, ex.: Certidão e Certidão Cancelada, Protocolo e Protocolo Cancelado
locais_de_rede = 
	IMAGENS\matricula,
	imagens\Protocolo,
	IMAGENS\CERTIDAO,
	IMAGENS\auxiliar,
	IMAGENS\CERTIDAO,
	imagens\Protocolo
caminho_temp_index = imagens\Temp_index
caminho_base = IMAGENS
caminho_backup = digitalizacao\CONFERENCIA DIGITALIZACAO
temp_index_usuario = 0067-2RGIRJ

# Os tipos de digitalização simples são no seguinte formato:
# {tipo}:{caminhoderede}:{subcaminho+nomearquivo.pdf ex.:aaaa\dd-mm\dd-mm-aaaa.pdf ou aaaa\mmm\dd-mm-aaaa.pdf}
tipos_digitalizacao_simples =
	CNIB:digitalizacao\CNIB:aaaa\mm-aaaa\ddmmaaaa.pdf,
	BIB:digitalizacao\BIB:aaaa\mm-aaaa\ddmmaaaa.pdf,
	OFICIO RECEBIDO:digitalizacao\OFICIO_RECEBIDO:aaaa\mm-aaaa\ddmmaaaa\numero_documento.pdf,
	OFICIO RECEBIDO ARIRJ:digitalizacao\OFICIO_RECEBIDO_ARIRJ:aaaa\mm-aaaa\ddmmaaaa\numero_documento.pdf,
	IMPEDIMENTO:digitalizacao\Impedimento\PASTA 44 (Impedimento PDF Apartir de 01.02.16):aaaa\mm-aaaa\ddmmaaaa\numero_documento.pdf,
	OFICIO EXPEDIDO:digitalizacao\Oficio_Expedido:aaaa\numero_documento.pdf,
	BOLETIM DE FREQUENCIA:digitalizacao\BOLETIM DE FREQUENCIA:aaaa\mm-aaaa\ddmmaaaa.pdf,
	FERIAS DO OFICIAL:digitalizacao\BOLETIM DE FREQUENCIA:aaaa\mm-aaaa\FERIAS\numero_documento.pdf,
	MALOTE DISTRIBUICAO:digitalizacao\OFICIOS DE DISTRIBUICAO:aaaa\mm-aaaa\ddmmaaaa\numero_documento.pdf,
	MAPA DE DISTRIBUICAO:digitalizacao\OFICIOS DE DISTRIBUICAO:aaaa\mm-aaaa\ddmmaaaa\MAPA.pdf

[LOCALIZACAO]
locale = pt_BR.UTF-8

[NAPS2]
caminho_naps2 = C:\Program Files\NAPS2\NAPS2.exe

